### ISSUE TITLE
found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]

### ISSUE THREAD

**Issue by jhpoelen** [qgroom/batinterations#2]
after running ```elton review --type note``` on a patched version of this repository (see https://github.com/qgroom/batinterations/pull/1), the following review notes were reported. (also see https://travis-ci.com/github/jhpoelen/batinterations/builds/163242535#L187)

reviewId | reviewDate | reviewer | namespace | reviewCommentType | reviewComment | archiveURI | referenceUrl | institutionCode | collectionCode | collectionId | catalogNumber | occurrenceId | sourceCitation | dataContext
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"59","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Cordia myxa"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"60","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Ficus bengalensis"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"61","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Melia azadirachta"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"62","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Melia azedarch"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"63","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Phoenix dactylifera"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"64","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Prosopis juliflora"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"65","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Terminalia catapa"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"66","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Ziziphus jujube"}}
e6382f3a-0b78-4717-a246-68a63cf7cdfb | 2020-05-01T18:10:48Z | GloBI automated reviewer (elton-0.3.5-SNAPSHOT) | local | note | found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf] |   |   |   |   |   |   |   | Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020. | {"reviewId":"e6382f3a-0b78-4717-a246-68a63cf7cdfb","reviewDate":"2020-05-01T18:10:48Z","reviewerName":"GloBI automated reviewer (elton-0.3.5-SNAPSHOT)","reviewCommentType":"note","reviewComment":"found malformed doi [http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf]","namespace":"local","context":{"argumentTypeId":"https://en.wiktionary.org/wiki/support","decimalLatitude":"26.810162","decimalLongitude":"55.898783","interactionTypeId":"http://purl.obolibrary.org/obo/RO_0002470","interactionTypeName":"eats","localityId":"GEONAMES:119373","localityName":"Qeshm Island, Iran","referenceCitation":"Zohoori, H., Kaibi, B. H., Karami, M., Khorasani, N., Dareshoori, B., & Dakhteh, M.H. (2007). Some observation on fruit used by birds and Egyptian fruit bat Rousettus aegyptiacus on Qeshm Island, Southern Iran. Podoces, 2(2), 156-9.","referenceDoi":"http://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","resourceLineNumber":"67","resourceURI":"file:/media/jorrit/data/globi/data/batinterations/./datasets/local/8a929c30295b9f174b5fe1183d46c2e79b11f85d3317f8e82eb2ad23c4d0319b","sourceTaxonName":"Rousettus aegyptiacus","studySourceCitation":"Quentin J. Groom. 2020. Bat interation data manually extracted from literature.. Accessed at <file:///media/jorrit/data/globi/data/batinterations/./> on 01 May 2020.","studyTitle":"localhttp://www.wesca.net/Podoces/Podoces2.2/Podoces%202_2_%20Birds%20&%20fruit%20bat%20feeding.pdf","targetBodyPartId":"http://purl.obolibrary.org/obo/PO_0009001","targetBodyPartName":"fruit","targetTaxonName":"Ziziphus spina-christi"}}

**Comment by qgroom** [comment]
The URL was in the wrong column, I've corrected it now.
